### PR TITLE
Display 3 most recent YouTube videos

### LINKED ISSUE #14: Display 3 most recent videos from YouTube.com
image

### PR DESCRIPTION
**Pull request by kpolitowicz**
Resolves #14 

The implementation is based on my previous work with meetup API, including the way I stubbed the API calls in tests (I just did not want to mix refactoring with new feature, but don't worry, I'll try to incorporate fake adapter pattern soon).

I was following the mockup as close as reasonably possible, so if you want some additional stuff (see below), let me know.

Live preview available at https://fast-citadel-66492.herokuapp.com/

1. View count and posted ago.

The API call to https://www.googleapis.com/youtube/v3/activities only gives publishedAt (which can be formatted to "posted ago" if you really wish to), but to get the views count, you need to make an additional call to https://www.googleapis.com/youtube/v3/videos/. I just wanted to keep it simple, so I am displaying publishedAt as string date/time. Let me know if you want it any other way.

2. Snippet images and links to the actual videos

The API offers the following img snippets:

```json
    "thumbnails": {
     "default": {
      "url": "https://i.ytimg.com/vi/S362bHXS8UI/default.jpg",
      "width": 120,
      "height": 90
     },
     "medium": {
      "url": "https://i.ytimg.com/vi/S362bHXS8UI/mqdefault.jpg",
      "width": 320,
      "height": 180
     },
     "high": {
      "url": "https://i.ytimg.com/vi/S362bHXS8UI/hqdefault.jpg",
      "width": 480,
      "height": 360
     },
     "standard": {
      "url": "https://i.ytimg.com/vi/S362bHXS8UI/sddefault.jpg",
      "width": 640,
      "height": 480
     },
     "maxres": {
      "url": "https://i.ytimg.com/vi/S362bHXS8UI/maxresdefault.jpg",
      "width": 1280,
      "height": 720
     }
    }
```

of which I'm using the smallest one, because this was the only one fitting into mockup dimensions (211x120).

Also, as per mockup, the snippets are no clickable - maybe it's worth adding direct links to those videos. But the again, it can be an issue for someone else to contribute. Again, let me know.

3. General styling.

The YT section styling is not the best. Let me know if you want to improve it (e.g. remove li bullet points). I can style it "my way", just wanted to check if you had any ideas in the meantime.

### CODE REVIEW

**Comment by nicholasjhenry** [comment]
Thank you, @kpolitowicz:

1. Re styling -- yes, makes sense to remove the bullets from the li tag, feel free to style it
2. Could we updated `app.json` for `YOUTUBE_API_KEY`.

Cheers!

**Comment by kpolitowicz** [comment]
@nicholasjhenry Sure. I added the key to ```app.json``` and removed bullet points, but I may have no time this week to do a better styling.

**Comment by nicholasjhenry** [comment]
That works for now, thank you @kpolitowicz.

**Comment by nicholasjhenry** [comment]
Thanks again, this has been deployed to production.

**Comment by kpolitowicz** [comment]
Yay! I'll try to improve the styling next week, unless you can interest somebody else in it :)

**Pull request merged**
