### PR TITLE
Added twitter dev config guide to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by kpolitowicz**
Hey! I've just went thru the process of configuring twitter in my dev env and thought it might be useful. A simple step-by-step guide how to go about the configuration.

### CODE REVIEW

**Comment by nicholasjhenry** [comment]
Great idea, @kpolitowicz. Could we move these setup instructions to the `README.md` of the `twitter` app. I like to keep related things together :-) Happy to keep a link from the Contributing guide to make it easier for new comers to find it. Thanks!

**Comment by kpolitowicz** [comment]
@nicholasjhenry Not sure if this is what you meant - feel free to correct it further, or even send me the README version you think would be better structured.

**Comment by nicholasjhenry** [comment]
Sorry, I should have given you a link: https://github.com/montrealelixir/website/blob/master/apps/twitter/README.md

**Comment by kpolitowicz** [comment]
@nicholasjhenry Well, I started doing it, but here's where things get complicated :) Twitter app is not even a hex package, just in-umbrella app and the config is done at the main project level (not even in montreal_elixir_web. As such, it seems to me the config instructions should be available in the main README.md (or CONTRIBUTING.md).

That said, I can put "getting twitter keys" part in the twitter app README and leave the rest of the config (dev.secret.exs and testing the server) in the main README. What do you think?

**Comment by nicholasjhenry** [comment]
Ah, let's leave it for now. Thanks for this.

**Pull request merged**
