### PR TITLE
Moved social feeds to ubmrella app

### PR DESCRIPTION
**Pull request by kpolitowicz**
This PR is meant as refactoring: moving the MontrealElixir.SocialFeeds context to its own umbrella app.

However, because of the move two improvements were convenient to make:

1. SocialFeeds.Cache now has clear/0 function; it is used in tests only (to make sure cache is empty before every test), but it generally makes sense to have this kind of functionality in production.
2. SocialFeeds.get_next_meetup_event/1 now accepts cache_ttl_in_msec option to give client (MontrealElixirWeb app) more control over the caching period for meetup API results.

Note: Now the SocialFeeds is a nice umbrella app, I'm going to try to use the adapter pattern for testing in the next PR.

### CODE REVIEW

**Comment by nicholasjhenry** [comment]
@kpolitowicz since we have a `twitter` app, what do think about naming this `meetup`?

**Comment by nicholasjhenry** [comment]
@kpolitowicz To clarify, we remove the `SocialFeeds` namespace.

**Comment by kpolitowicz** [comment]
Hmm @nicholasjhenry, good point. But, when I started working on SocialFeeds I planned it to be a home for all external services (including twitter). Since @frahugo implemented twitter differently (good job BTW), it does make less sense now, however it still could contain youtube functionality. And anything else that may need external API calls and cache.

We could have a separate youtube and meetup apps, but for just one call in each one isn't it a bit of over-engineering? Also, they would need to either have a separate cache process or depend on the 3rd cache app.
We could also rename SocialFeeds to something like ExternalFeeds or ExternalApiClients.
Or we could keep SocialFeeds as a context (discarding this PR).

Last but not least, I would like to avoid changing too much in this particular PR, as it was only meant as refactoring.
What do you think?

**Comment by nicholasjhenry** [comment]
All makes sense to me @kpolitowicz! Thanks

**Pull request merged**
